### ISSUE TITLE
Can you add code to print out the info required?

### ISSUE THREAD

**Issue by Cli98** [snehal62/N-queen#1]
Hi @snehal62 ,

I checked your code and awesome! Can you consider to add code to print out all required result for the project? I did not see the way to do this for now. And we can simply not start with documentation if those information is not available. 

And project 2 requires in-line documentation.

Thank you,

**Comment by snehal62** [comment]
Can you please specify what type of required result you are looking for, I
don’t get this can u please specify?

**Comment by Cli98** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/19630616/99180924-8cbeee00-26f8-11eb-8c4f-9a6cc52e097e.png">

@snehal62 Please provide code to print out those result.
